//
//  RecurringTransaction.swift
//  FinTrack
//
//  Defines a recurring transaction rule. Each rule generates actual Transaction
//  entries on a schedule. The rule stores the "next due date" and advances it
//  every time a transaction is generated.
//

import Foundation
import SwiftData

// MARK: - Frequency

enum RecurrenceFrequency: String, CaseIterable, Identifiable {
    case daily      // Quotidien
    case weekly     // Hebdomadaire
    case biweekly   // Toutes les 2 semaines
    case monthly    // Mensuel
    case quarterly  // Trimestriel
    case yearly     // Annuel

    var id: String { rawValue }

    var label: String {
        switch self {
        case .daily:     return LanguageManager.shared["recurring.freq.daily"]
        case .weekly:    return LanguageManager.shared["recurring.freq.weekly"]
        case .biweekly:  return LanguageManager.shared["recurring.freq.biweekly"]
        case .monthly:   return LanguageManager.shared["recurring.freq.monthly"]
        case .quarterly: return LanguageManager.shared["recurring.freq.quarterly"]
        case .yearly:    return LanguageManager.shared["recurring.freq.yearly"]
        }
    }

    var shortLabel: String {
        switch self {
        case .daily:     return LanguageManager.shared["recurring.freq.s.daily"]
        case .weekly:    return LanguageManager.shared["recurring.freq.s.weekly"]
        case .biweekly:  return LanguageManager.shared["recurring.freq.s.biweekly"]
        case .monthly:   return LanguageManager.shared["recurring.freq.s.monthly"]
        case .quarterly: return LanguageManager.shared["recurring.freq.s.quarterly"]
        case .yearly:    return LanguageManager.shared["recurring.freq.s.yearly"]
        }
    }

    /// Approximate number of occurrences per month (for monthly-equivalent math).
    var approxPeriodsPerMonth: Double {
        switch self {
        case .daily:     return 365.0 / 12.0
        case .weekly:    return 52.0 / 12.0
        case .biweekly:  return 26.0 / 12.0
        case .monthly:   return 1.0
        case .quarterly: return 1.0 / 3.0
        case .yearly:    return 1.0 / 12.0
        }
    }

    /// Compact per-period unit suffix, e.g. "/sem.", "/mois".
    var unitSuffix: String {
        switch self {
        case .daily:     return LanguageManager.shared["freq.unit.daily"]
        case .weekly:    return LanguageManager.shared["freq.unit.weekly"]
        case .biweekly:  return LanguageManager.shared["freq.unit.biweekly"]
        case .monthly:   return LanguageManager.shared["freq.unit.monthly"]
        case .quarterly: return LanguageManager.shared["freq.unit.quarterly"]
        case .yearly:    return LanguageManager.shared["freq.unit.yearly"]
        }
    }

    var iconSystemName: String {
        switch self {
        case .daily:     return "clock.arrow.2.circlepath"
        case .weekly:    return "calendar"
        case .biweekly:  return "calendar.badge.clock"
        case .monthly:   return "calendar.circle.fill"
        case .quarterly: return "calendar.badge.checkmark"
        case .yearly:    return "calendar.badge.plus"
        }
    }

    /// Returns the date of the next occurrence after `date`, using Calendar to
    /// handle month-length variations (28/29/30/31) correctly.
    func nextDate(after date: Date) -> Date {
        let cal = Calendar.current
        switch self {
        case .daily:     return cal.date(byAdding: .day,   value: 1,  to: date) ?? date
        case .weekly:    return cal.date(byAdding: .day,   value: 7,  to: date) ?? date
        case .biweekly:  return cal.date(byAdding: .day,   value: 14, to: date) ?? date
        case .monthly:   return cal.date(byAdding: .month, value: 1,  to: date) ?? date
        case .quarterly: return cal.date(byAdding: .month, value: 3,  to: date) ?? date
        case .yearly:    return cal.date(byAdding: .year,  value: 1,  to: date) ?? date
        }
    }
}

// MARK: - Model

@Model
final class RecurringTransaction {
    /// User-facing label. If blank, the UI falls back to payee or category name.
    var title: String = ""
    var amount: Decimal = 0     // always positive
    var typeRaw: String = TransactionType.expense.rawValue
    var frequencyRaw: String = RecurrenceFrequency.monthly.rawValue

    /// Date of the first desired occurrence. `nextDueDate` is initialised to this.
    var startDate: Date = Date.now

    /// The date the manager will generate the NEXT transaction. Advances after
    /// each generation. This is the single field the manager watches.
    var nextDueDate: Date = Date.now

    /// If set, no transactions are generated after this date.
    var endDate: Date?

    /// Pausing a rule stops generation without deleting it.
    var isActive: Bool = true
    // MARK: Notification settings
    var notificationEnabled: Bool = false
    var notificationDaysBefore: Int = 3


    /// true when auto-generated by a Loan — excluded from expense lines
    /// in CashFlowCalculator to avoid double-counting with loanLines.
    var isLoanPayment: Bool = false
    /// true when auto-generated by a CreditLine — excluded from expense lines
    /// in CashFlowCalculator to avoid double-counting with creditLineLines.
    var isCreditLinePayment: Bool = false
    var isTransfer: Bool = false          // true = generates two linked transactions

    var note: String = ""
    var payee: String?
    var createdAt: Date = Date.now

    @Relationship(deleteRule: .nullify, inverse: \Account.recurringRules)
    var account: Account?
    @Relationship(deleteRule: .nullify, inverse: \Account.incomingTransfers)
    var destinationAccount: Account? = nil   // target account for transfers
    @Relationship(deleteRule: .nullify, inverse: \Category.recurringRules)
    var category: Category?

    /// Savings project that owns this rule (auto-transfer). nil = standalone rule.
    @Relationship(deleteRule: .nullify, inverse: \SavingsProject.recurringTransactions)
    var savingsProject: SavingsProject? = nil

    /// Concrete transactions generated by this rule (reliable scoped edit/delete).
    var generatedTransactions: [Transaction]? = []

    // MARK: Computed

    var type: TransactionType {
        get { TransactionType(rawValue: typeRaw) ?? .expense }
        set { typeRaw = newValue.rawValue }
    }

    var frequency: RecurrenceFrequency {
        get { RecurrenceFrequency(rawValue: frequencyRaw) ?? .monthly }
        set { frequencyRaw = newValue.rawValue }
    }

    /// Display name for the rule: explicit title > payee > category > generic.
    var displayTitle: String {
        if !title.trimmingCharacters(in: .whitespaces).isEmpty { return title }
        if let p = payee, !p.isEmpty { return p }
        if let c = category { return c.name }
        return type == .income ? LanguageManager.shared["tx.type.income"] : LanguageManager.shared["tx.type.expense"]
    }

    /// Human-readable relative label for nextDueDate.
    var dueDateLabel: String {
        let cal = Calendar.current
        let today = cal.startOfDay(for: .now)
        let due   = cal.startOfDay(for: nextDueDate)
        let days  = cal.dateComponents([.day], from: today, to: due).day ?? 0
        switch days {
        case ..<0:   return LanguageManager.shared["recurring.overdue"]
        case 0:      return LanguageManager.shared["recurring.dueToday"]
        case 1:      return LanguageManager.shared["recurring.dueTomorrow"]
        case 2...6:  return LanguageManager.shared.f("recurring.dueInDays", days)
        default:
            let fmt = FormatterCache.datePattern("d MMM", locale: LanguageManager.shared.locale)
            return fmt.string(from: nextDueDate)
        }
    }

    /// Colour cue for urgency of the next due date.
    var dueDateColor: DueDateColor {
        let cal = Calendar.current
        let today = cal.startOfDay(for: .now)
        let due   = cal.startOfDay(for: nextDueDate)
        let days  = cal.dateComponents([.day], from: today, to: due).day ?? 0
        switch days {
        case ..<0: return .overdue
        case 0...2: return .soon
        default:   return .normal
        }
    }

    enum DueDateColor {
        case overdue, soon, normal
    }

    // MARK: Init

    init(
        title: String = "",
        amount: Decimal,
        type: TransactionType,
        frequency: RecurrenceFrequency,
        startDate: Date,
        endDate: Date? = nil,
        account: Account? = nil,
        category: Category? = nil,
        note: String = "",
        payee: String? = nil,
        isLoanPayment: Bool = false,
        isCreditLinePayment: Bool = false
    ) {
        self.title = title
        self.amount = amount
        self.typeRaw = type.rawValue
        self.frequencyRaw = frequency.rawValue
        self.startDate = startDate
        self.nextDueDate = startDate
        self.endDate = endDate
        self.isActive = true
        self.isLoanPayment = false
        self.isCreditLinePayment = false
        self.note = note
        self.payee = payee
        self.isLoanPayment = isLoanPayment
        self.isCreditLinePayment = isCreditLinePayment
        self.createdAt = .now
        self.account = account
        self.category = category
    }
}
