//
//  SavingsProject.swift
//  FinTrack
//

import Foundation
import SwiftData

@Model
final class SavingsProject {
    var name: String = ""
    var iconSystemName: String = "star.fill"
    var colorHex: String = "#3478F6"
    var currency: String = "CAD"

    /// Amount already saved (manually maintained, OR derived from linked account).
    var manualCurrentAmount: Decimal = 0
    /// If true, currentAmount is read from the linked account's balance.
    var trackViaAccount: Bool = false

    /// nil = open-ended accumulation (no finish line).
    var targetAmount: Decimal?

    /// Fixed monthly contribution assigned from surplus.
    var monthlyContribution: Decimal = 0

    // MARK: Auto-transfer configuration
    /// When true, a linked RecurringTransaction materialises contributions automatically.
    var autoTransferEnabled: Bool = false
    var transferFrequencyRaw: String = RecurrenceFrequency.monthly.rawValue
    /// Day of month (monthly) or weekday 1=Sun...7=Sat (weekly/biweekly).
    var transferDay: Int = 1

    /// Optional deadline. When set, drives the required contribution calculation.
    var targetDate: Date?

    var notes: String?
    var isActive: Bool = true
    var createdAt: Date = Date.now

    /// Optional savings account (e.g., a dedicated TFSA or FHSA).
    @Relationship(deleteRule: .nullify, inverse: \Account.savingsProjects)
    var account: Account?

    /// Source account debited by auto-transfers (where the money comes FROM).
    @Relationship(deleteRule: .nullify, inverse: \Account.savingsSourceProjects)
    var sourceAccount: Account? = nil

    /// Recurring rule(s) materialising this project's contributions.
    var recurringTransactions: [RecurringTransaction]? = []
    /// Transactions generated by those rules (for reliable disable/cleanup).
    var generatedTransactions: [Transaction]? = []

    // MARK: Computed

    var transferFrequency: RecurrenceFrequency {
        get { RecurrenceFrequency(rawValue: transferFrequencyRaw) ?? .monthly }
        set { transferFrequencyRaw = newValue.rawValue }
    }

    /// Monthly-equivalent of the per-transfer contribution (amount x periods/month),
    /// used for projections, time-to-target and cash-flow. `monthlyContribution`
    /// itself holds the amount moved per transfer at `transferFrequency`.
    var monthlyEquivalentContribution: Decimal {
        monthlyContribution * Decimal(transferFrequency.approxPeriodsPerMonth)
    }

    var currentAmount: Decimal {
        trackViaAccount ? (account?.balance ?? manualCurrentAmount) : manualCurrentAmount
    }

    var amountRemaining: Decimal? {
        guard let target = targetAmount else { return nil }
        return max(0, target - currentAmount)
    }

    var progressFraction: Double {
        guard let target = targetAmount, (target as NSDecimalNumber).doubleValue > 0 else { return 0 }
        let ratio = ((currentAmount / target) as NSDecimalNumber).doubleValue
        return min(1, max(0, ratio))
    }

    /// Months until target is reached at current contribution rate.
    var monthsToTarget: Int? {
        guard let remaining = amountRemaining,
              remaining > 0,
              monthlyEquivalentContribution > 0 else { return nil }
        let months = ((remaining / monthlyEquivalentContribution) as NSDecimalNumber).doubleValue
        return Int(ceil(months))
    }

    var targetReachDate: Date? {
        guard let months = monthsToTarget else { return nil }
        return Calendar.current.date(byAdding: .month, value: months, to: .now)
    }

    /// Monthly contribution required to hit targetAmount by targetDate.
    var requiredMonthlyForDeadline: Decimal? {
        guard let target = targetAmount, let deadline = targetDate else { return nil }
        let remaining = max(0, target - currentAmount)
        guard (remaining as NSDecimalNumber).doubleValue > 0 else { return 0 }
        let months = Calendar.current.dateComponents([.month], from: .now, to: deadline).month ?? 0
        guard months > 0 else { return remaining }
        return (remaining / Decimal(months)).rounded(scale: 2)
    }

    /// Label summarising the projection status.
    var projectionLabel: String {
        let L = LanguageManager.shared
        if progressFraction >= 1 { return L["savings.projlabel.reached"] }
        if let d = targetReachDate {
            let fmt = FormatterCache.datePattern("MMMM yyyy", locale: L.locale)
            return String(format: L["savings.projlabel.reachedIn"], fmt.string(from: d))
        }
        if targetAmount == nil {
            let perTransfer = (monthlyContribution as NSDecimalNumber).doubleValue
            if perTransfer > 0 {
                let amt = monthlyContribution.formatted(asCurrency: currency) + transferFrequency.unitSuffix
                return String(format: L["savings.projlabel.freeAccum"], amt)
            }
        }
        return L["savings.projlabel.undefined"]
    }

    // MARK: Init

    init(
        name: String,
        iconSystemName: String = "star.fill",
        colorHex: String = "#3478F6",
        currency: String = Currencies.default,
        currentAmount: Decimal = 0,
        trackViaAccount: Bool = false,
        targetAmount: Decimal? = nil,
        monthlyContribution: Decimal = 0,
        targetDate: Date? = nil,
        account: Account? = nil,
        notes: String? = nil
    ) {
        self.name = name
        self.iconSystemName = iconSystemName
        self.colorHex = colorHex
        self.currency = currency
        self.manualCurrentAmount = currentAmount
        self.trackViaAccount = trackViaAccount
        self.targetAmount = targetAmount
        self.monthlyContribution = monthlyContribution
        self.targetDate = targetDate
        self.account = account
        self.notes = notes
        self.isActive = true
        self.createdAt = .now
    }
}

private extension Decimal {
    func rounded(scale: Int) -> Decimal {
        var result = Decimal()
        var mutable = self
        NSDecimalRound(&result, &mutable, scale, .plain)
        return result
    }
}
