//
//  LocalizedStrings.swift
//  FinTrack
//
//  All UI strings for FR / EN / ES / PT-BR.
//  Keys use dot-notation: "section.element"
//  Format placeholders: %@ (string), %d (int), %1$@ (positional)
//

enum LocalizedStrings {

    static func resolve(key: String, language: String) -> String {
        strings[key]?[language]
            ?? strings[key]?["fr"]  // French fallback
            ?? key                  // key itself as last resort
    }

    // swiftlint:disable line_length
    static let strings: [String: [String: String]] = [

        // MARK: - Tabs
        "tab.dashboard":    ["fr": "Tableau de bord", "en": "Dashboard",        "es": "Panel",         "pt": "Painel"],
        "tab.accounts":     ["fr": "Comptes",          "en": "Accounts",         "es": "Cuentas",       "pt": "Contas"],
        "tab.transactions": ["fr": "Transactions",     "en": "Transactions",     "es": "Transacciones", "pt": "Transações"],
        "tab.settings":     ["fr": "Réglages",         "en": "Settings",         "es": "Ajustes",       "pt": "Configurações"],

        // MARK: - Common actions
        "action.save":       ["fr": "Enregistrer",         "en": "Save",         "es": "Guardar",     "pt": "Salvar"],
        "action.cancel":     ["fr": "Annuler",             "en": "Cancel",       "es": "Cancelar",    "pt": "Cancelar"],
        "action.delete":     ["fr": "Supprimer",           "en": "Delete",       "es": "Eliminar",    "pt": "Excluir"],
        "action.edit":       ["fr": "Modifier",            "en": "Edit",         "es": "Editar",      "pt": "Editar"],
        "action.add":        ["fr": "Ajouter",             "en": "Add",          "es": "Añadir",      "pt": "Adicionar"],
        "action.close":      ["fr": "Fermer",              "en": "Close",        "es": "Cerrar",      "pt": "Fechar"],
        "action.seeAll":     ["fr": "Tout voir",           "en": "See All",      "es": "Ver todo",    "pt": "Ver tudo"],
        "action.archive":    ["fr": "Archiver",            "en": "Archive",      "es": "Archivar",    "pt": "Arquivar"],
        "action.unarchive":  ["fr": "Désarchiver",         "en": "Unarchive",    "es": "Desarchivar", "pt": "Desarquivar"],
        "action.pause":      ["fr": "Mettre en pause",     "en": "Pause",        "es": "Pausar",      "pt": "Pausar"],
        "action.resume":     ["fr": "Réactiver",           "en": "Resume",       "es": "Reactivar",   "pt": "Reativar"],
        "action.confirm":    ["fr": "Confirmer",           "en": "Confirm",      "es": "Confirmar",   "pt": "Confirmar"],
        "action.search":     ["fr": "Rechercher",          "en": "Search",       "es": "Buscar",      "pt": "Pesquisar"],
        "action.generateNow":["fr": "Générer maintenant",  "en": "Generate Now", "es": "Generar ahora","pt": "Gerar agora"],

        // MARK: - Common labels
        "label.currency":    ["fr": "Devise",            "en": "Currency",       "es": "Moneda",       "pt": "Moeda"],
        "label.amount":      ["fr": "Montant",           "en": "Amount",         "es": "Monto",        "pt": "Valor"],
        "label.date":        ["fr": "Date",              "en": "Date",           "es": "Fecha",        "pt": "Data"],
        "label.note":        ["fr": "Note",              "en": "Note",           "es": "Nota",         "pt": "Nota"],
        "label.name":        ["fr": "Nom",               "en": "Name",           "es": "Nombre",       "pt": "Nome"],
        "label.type":        ["fr": "Type",              "en": "Type",           "es": "Tipo",         "pt": "Tipo"],
        "label.account":     ["fr": "Compte",            "en": "Account",        "es": "Cuenta",       "pt": "Conta"],
        "label.category":    ["fr": "Catégorie",         "en": "Category",       "es": "Categoría",    "pt": "Categoria"],
        "label.institution": ["fr": "Institution",       "en": "Institution",    "es": "Institución",  "pt": "Instituição"],
        "label.notes":       ["fr": "Notes",             "en": "Notes",          "es": "Notas",        "pt": "Notas"],
        "label.balance":     ["fr": "Solde",             "en": "Balance",        "es": "Saldo",        "pt": "Saldo"],
        "label.income":      ["fr": "Revenu",            "en": "Income",         "es": "Ingreso",      "pt": "Receita"],
        "label.expense":     ["fr": "Dépense",           "en": "Expense",        "es": "Gasto",        "pt": "Despesa"],
        "label.incomes":     ["fr": "Revenus",           "en": "Income",         "es": "Ingresos",     "pt": "Receitas"],
        "label.expenses":    ["fr": "Dépenses",          "en": "Expenses",       "es": "Gastos",       "pt": "Despesas"],
        "label.total":       ["fr": "Total",             "en": "Total",          "es": "Total",        "pt": "Total"],
        "label.none":        ["fr": "Aucune",            "en": "None",           "es": "Ninguna",      "pt": "Nenhuma"],
        "label.optional":    ["fr": "(optionnel)",       "en": "(optional)",     "es": "(opcional)",   "pt": "(opcional)"],
        "label.color":       ["fr": "Couleur",           "en": "Color",          "es": "Color",        "pt": "Cor"],
        "label.icon":        ["fr": "Icône",             "en": "Icon",           "es": "Ícono",        "pt": "Ícone"],
        "label.lender":      ["fr": "Prêteur",           "en": "Lender",         "es": "Prestamista",  "pt": "Credor"],
        "label.rate":        ["fr": "Taux",              "en": "Rate",           "es": "Tasa",         "pt": "Taxa"],
        "label.frequency":   ["fr": "Fréquence",         "en": "Frequency",      "es": "Frecuencia",   "pt": "Frequência"],
        "label.payee":       ["fr": "Bénéficiaire",      "en": "Payee",          "es": "Beneficiario", "pt": "Beneficiário"],
        "label.source":      ["fr": "Source",            "en": "Source",         "es": "Fuente",       "pt": "Fonte"],
        "label.details":     ["fr": "Détails",           "en": "Details",        "es": "Detalles",     "pt": "Detalhes"],
        "label.information": ["fr": "Informations",      "en": "Information",    "es": "Información",  "pt": "Informações"],
        "label.appearance":  ["fr": "Apparence",         "en": "Appearance",     "es": "Apariencia",   "pt": "Aparência"],
        "label.advanced":    ["fr": "Options avancées",  "en": "Advanced Options","es": "Opciones avanzadas","pt": "Opções avançadas"],
        "label.hideAdvanced":["fr": "Masquer options avancées","en": "Hide Advanced","es": "Ocultar opciones","pt": "Ocultar avançado"],
        "label.today":       ["fr": "Aujourd'hui",       "en": "Today",          "es": "Hoy",          "pt": "Hoje"],
        "label.yesterday":   ["fr": "Hier",              "en": "Yesterday",      "es": "Ayer",         "pt": "Ontem"],
        "label.all":         ["fr": "Tout",              "en": "All",            "es": "Todo",         "pt": "Tudo"],
        "label.active":      ["fr": "Actif",             "en": "Active",         "es": "Activo",       "pt": "Ativo"],
        "label.payment":     ["fr": "Versement",         "en": "Payment",        "es": "Pago",         "pt": "Pagamento"],
        "label.months":      ["fr": "%d mois",           "en": "%d months",      "es": "%d meses",     "pt": "%d meses"],
        "label.perMonth":    ["fr": "/mois",             "en": "/month",         "es": "/mes",         "pt": "/mês"],
        "label.available":   ["fr": "Disponible",        "en": "Available",      "es": "Disponible",   "pt": "Disponível"],

        // MARK: - Dashboard
        "dashboard.title":           ["fr": "Tableau de bord",    "en": "Dashboard",         "es": "Panel",             "pt": "Painel"],
        "dashboard.globalBalance":   ["fr": "Solde global",       "en": "Total Balance",      "es": "Saldo global",      "pt": "Saldo total"],
        "dashboard.myAccounts":      ["fr": "Mes comptes",        "en": "My Accounts",        "es": "Mis cuentas",       "pt": "Minhas contas"],
        "dashboard.recentTx":        ["fr": "Transactions récentes","en": "Recent Transactions","es": "Transacciones recientes","pt": "Transações recentes"],
        "dashboard.noTx":            ["fr": "Aucune transaction pour le moment.\nAppuyez sur + pour en ajouter une.", "en": "No transactions yet.\nTap + to add one.", "es": "Sin transacciones aún.\nToca + para añadir una.", "pt": "Sem transações ainda.\nToque em + para adicionar."],
        "dashboard.upcoming":        ["fr": "À venir (30 jours)", "en": "Upcoming (30 days)", "es": "Próximos (30 días)", "pt": "Próximos (30 dias)"],
        "dashboard.myLoans":         ["fr": "Mes prêts",          "en": "My Loans",           "es": "Mis préstamos",     "pt": "Meus empréstimos"],
        "dashboard.myCreditLines":   ["fr": "Mes marges de crédit","en": "My Credit Lines",   "es": "Mis líneas de crédito","pt": "Minhas linhas de crédito"],
        "dashboard.welcome.title":   ["fr": "Bienvenue dans FinTrack","en": "Welcome to FinTrack","es": "Bienvenido a FinTrack","pt": "Bem-vindo ao FinTrack"],
        "dashboard.welcome.subtitle":["fr": "Commencez par ajouter un compte bancaire,\nune carte ou un portefeuille liquide.", "en": "Start by adding a bank account,\na card, or a cash wallet.", "es": "Comienza añadiendo una cuenta bancaria,\ntarjeta o efectivo.", "pt": "Comece adicionando uma conta bancária,\ncartão ou carteira de dinheiro."],
        "dashboard.welcome.cta":     ["fr": "Ajouter mon premier compte","en": "Add My First Account","es": "Añadir mi primera cuenta","pt": "Adicionar minha primeira conta"],
        "dashboard.thisMonth":       ["fr": "Ce mois-ci",         "en": "This Month",         "es": "Este mes",          "pt": "Este mês"],

        // MARK: - Accounts
        "account.title":           ["fr": "Comptes",               "en": "Accounts",            "es": "Cuentas",              "pt": "Contas"],
        "account.myAccounts":      ["fr": "Mes comptes",           "en": "My Accounts",          "es": "Mis cuentas",          "pt": "Minhas contas"],
        "account.archived":        ["fr": "Comptes archivés (%d)", "en": "Archived (%d)",        "es": "Archivados (%d)",      "pt": "Arquivados (%d)"],
        "account.noAccounts":      ["fr": "Aucun compte",          "en": "No Accounts",          "es": "Sin cuentas",          "pt": "Sem contas"],
        "account.noAccounts.sub":  ["fr": "Appuyez sur + pour ajouter un compte.", "en": "Tap + to add an account.", "es": "Toca + para añadir una cuenta.", "pt": "Toque em + para adicionar uma conta."],
        "account.create":          ["fr": "Nouveau compte",        "en": "New Account",          "es": "Nueva cuenta",         "pt": "Nova conta"],
        "account.edit":            ["fr": "Modifier le compte",    "en": "Edit Account",         "es": "Editar cuenta",        "pt": "Editar conta"],
        "account.initialBalance":  ["fr": "Solde initial",         "en": "Initial Balance",      "es": "Saldo inicial",        "pt": "Saldo inicial"],
        "account.archivePrompt":   ["fr": "Archiver ce compte ?",  "en": "Archive this account?","es": "¿Archivar esta cuenta?","pt": "Arquivar esta conta?"],
        "account.unarchivePrompt": ["fr": "Désarchiver ce compte ?","en": "Unarchive account?",  "es": "¿Desarchivar cuenta?", "pt": "Desarquivar conta?"],
        "account.archiveFooter":   ["fr": "L'archivage masque le compte sans supprimer ses transactions. Les soldes globaux ne tiennent plus compte d'un compte archivé.", "en": "Archiving hides the account without deleting its transactions. Global balances no longer include archived accounts.", "es": "Archivar oculta la cuenta sin eliminar sus transacciones. Los saldos globales ya no incluyen cuentas archivadas.", "pt": "Arquivar oculta a conta sem excluir suas transações. Os saldos globais não incluem mais contas arquivadas."],
        "account.deleteDefinitive":["fr": "Supprimer définitivement","en": "Delete Permanently", "es": "Eliminar definitivamente","pt": "Excluir definitivamente"],
        "account.deleteFooter":    ["fr": "La suppression efface ce compte et toutes ses transactions. Préférez l'archivage si vous souhaitez les conserver.", "en": "Deletion removes this account and all its transactions. Prefer archiving to keep them.", "es": "Eliminar borra esta cuenta y todas sus transacciones. Prefiere archivar para conservarlas.", "pt": "Excluir apaga esta conta e todas as suas transações. Prefira arquivar para mantê-las."],
        "account.noTransactions":  ["fr": "Aucune transaction sur ce compte.", "en": "No transactions on this account.", "es": "Sin transacciones en esta cuenta.", "pt": "Sem transações nesta conta."],
        "account.newTransaction":  ["fr": "Nouvelle transaction",  "en": "New Transaction",      "es": "Nueva transacción",    "pt": "Nova transação"],
        "account.type.checking":   ["fr": "Compte courant",        "en": "Checking",             "es": "Cuenta corriente",     "pt": "Conta corrente"],
        "account.type.savings":    ["fr": "Épargne",               "en": "Savings",              "es": "Ahorro",               "pt": "Poupança"],
        "account.type.credit":     ["fr": "Carte de crédit",       "en": "Credit Card",          "es": "Tarjeta de crédito",   "pt": "Cartão de crédito"],
        "account.type.cash":       ["fr": "Liquide",               "en": "Cash",                 "es": "Efectivo",             "pt": "Dinheiro"],
        "account.type.investment": ["fr": "Placement",             "en": "Investment",           "es": "Inversión",            "pt": "Investimento"],
        "account.type.other":      ["fr": "Autre",                 "en": "Other",                "es": "Otro",                 "pt": "Outro"],

        // MARK: - Transactions
        "tx.title":           ["fr": "Transactions",      "en": "Transactions",      "es": "Transacciones",   "pt": "Transações"],
        "tx.allAccounts":     ["fr": "Tous les comptes",  "en": "All Accounts",      "es": "Todas las cuentas","pt": "Todas as contas"],
        "tx.create":          ["fr": "Nouvelle transaction","en": "New Transaction", "es": "Nueva transacción","pt": "Nova transação"],
        "tx.edit":            ["fr": "Modifier la transaction","en": "Edit Transaction","es": "Editar transacción","pt": "Editar transação"],
        "tx.deletePrompt":    ["fr": "Supprimer cette transaction ?","en": "Delete this transaction?","es": "¿Eliminar esta transacción?","pt": "Excluir esta transação?"],
        "tx.noTx":            ["fr": "Aucune transaction", "en": "No Transactions",  "es": "Sin transacciones","pt": "Sem transações"],
        "tx.noTx.sub":        ["fr": "Ajoutez une transaction depuis le tableau de bord ou un compte.", "en": "Add a transaction from the dashboard or an account.", "es": "Añade una transacción desde el panel o una cuenta.", "pt": "Adicione uma transação pelo painel ou uma conta."],
        "tx.payeeExpense":    ["fr": "Bénéficiaire (commerce, personne…)","en": "Payee (store, person…)","es": "Beneficiario (tienda, persona…)","pt": "Beneficiário (loja, pessoa…)"],
        "tx.payeeIncome":     ["fr": "Source (employeur, client…)","en": "Source (employer, client…)","es": "Fuente (empleador, cliente…)","pt": "Fonte (empregador, cliente…)"],
        "tx.noCategory":      ["fr": "Aucune catégorie",   "en": "No Category",      "es": "Sin categoría",   "pt": "Sem categoria"],
        "tx.type.income":     ["fr": "Revenu",             "en": "Income",           "es": "Ingreso",         "pt": "Receita"],
        "tx.type.expense":    ["fr": "Dépense",            "en": "Expense",          "es": "Gasto",           "pt": "Despesa"],

        // MARK: - Recurring
        "recurring.title":        ["fr": "Récurrences",          "en": "Recurring",           "es": "Recurrentes",        "pt": "Recorrências"],
        "recurring.active":       ["fr": "Actives (%d)",         "en": "Active (%d)",         "es": "Activas (%d)",       "pt": "Ativas (%d)"],
        "recurring.paused":       ["fr": "En pause (%d)",        "en": "Paused (%d)",         "es": "Pausadas (%d)",      "pt": "Pausadas (%d)"],
        "recurring.create":       ["fr": "Nouvelle récurrence",  "en": "New Recurring",       "es": "Nueva recurrencia",  "pt": "Nova recorrência"],
        "recurring.edit":         ["fr": "Modifier la récurrence","en": "Edit Recurring",     "es": "Editar recurrencia", "pt": "Editar recorrência"],
        "recurring.deletePrompt": ["fr": "Supprimer cette récurrence ?","en": "Delete this recurring rule?","es": "¿Eliminar esta recurrencia?","pt": "Excluir esta recorrência?"],
        "recurring.deleteFooter": ["fr": "Supprime la règle uniquement. Les transactions déjà enregistrées sont conservées.", "en": "Deletes the rule only. Already recorded transactions are kept.", "es": "Elimina solo la regla. Las transacciones ya registradas se conservan.", "pt": "Exclui apenas a regra. As transações já registradas são mantidas."],
        "recurring.schedule":     ["fr": "Planification",        "en": "Schedule",            "es": "Planificación",      "pt": "Agendamento"],
        "recurring.name":         ["fr": "Nom (ex. Salaire BNC, Loyer)","en": "Name (e.g. Salary, Rent)","es": "Nombre (ej. Salario, Alquiler)","pt": "Nome (ex. Salário, Aluguel)"],
        "recurring.firstOccurrence":["fr":"Première occurrence", "en": "First Occurrence",    "es": "Primera ocurrencia", "pt": "Primeira ocorrência"],
        "recurring.endDate":      ["fr": "Date de fin",          "en": "End Date",            "es": "Fecha de fin",       "pt": "Data de fim"],
        "recurring.activeToggle": ["fr": "Récurrence active",    "en": "Active",              "es": "Activa",             "pt": "Ativa"],
        "recurring.pausedToggle": ["fr": "Récurrence en pause",  "en": "Paused",              "es": "Pausada",            "pt": "Pausada"],
        "recurring.activeFooter": ["fr": "Les transactions seront générées automatiquement aux échéances.", "en": "Transactions will be generated automatically at each due date.", "es": "Las transacciones se generarán automáticamente en cada fecha.", "pt": "As transações serão geradas automaticamente em cada data de vencimento."],
        "recurring.pausedFooter": ["fr": "La génération est suspendue. Aucune transaction ne sera créée jusqu'à la réactivation.", "en": "Generation is paused. No transactions will be created until reactivated.", "es": "La generación está pausada. No se crearán transacciones hasta reactivar.", "pt": "A geração está pausada. Nenhuma transação será criada até reativação."],
        "recurring.empty.title":  ["fr": "Aucune récurrence",    "en": "No Recurring Rules",  "es": "Sin recurrencias",   "pt": "Sem recorrências"],
        "recurring.empty.sub":    ["fr": "Ajoutez votre salaire, vos abonnements ou tout paiement régulier. FinTrack les enregistrera automatiquement à chaque échéance.", "en": "Add your salary, subscriptions, or any regular payment. FinTrack will record them automatically.", "es": "Añade tu salario, suscripciones o cualquier pago regular. FinTrack los registrará automáticamente.", "pt": "Adicione seu salário, assinaturas ou qualquer pagamento regular. O FinTrack os registrará automaticamente."],
        "recurring.overdue":      ["fr": "En retard",            "en": "Overdue",             "es": "Vencido",            "pt": "Vencido"],
        "recurring.dueToday":     ["fr": "Aujourd'hui",          "en": "Today",               "es": "Hoy",                "pt": "Hoje"],
        "recurring.dueTomorrow":  ["fr": "Demain",               "en": "Tomorrow",            "es": "Mañana",             "pt": "Amanhã"],
        "recurring.dueInDays":    ["fr": "Dans %d jours",        "en": "In %d days",          "es": "En %d días",         "pt": "Em %d dias"],
        "recurring.freq.daily":   ["fr": "Quotidien",            "en": "Daily",               "es": "Diario",             "pt": "Diário"],
        "recurring.freq.weekly":  ["fr": "Hebdomadaire",         "en": "Weekly",              "es": "Semanal",            "pt": "Semanal"],
        "recurring.freq.biweekly":["fr": "Toutes les 2 semaines","en": "Every 2 Weeks",       "es": "Cada 2 semanas",     "pt": "A cada 2 semanas"],
        "recurring.freq.monthly": ["fr": "Mensuel",              "en": "Monthly",             "es": "Mensual",            "pt": "Mensal"],
        "recurring.freq.quarterly":["fr":"Trimestriel",          "en": "Quarterly",           "es": "Trimestral",         "pt": "Trimestral"],
        "recurring.freq.yearly":  ["fr": "Annuel",               "en": "Yearly",              "es": "Anual",              "pt": "Anual"],
        "recurring.freq.s.daily": ["fr": "/ jour",               "en": "/ day",               "es": "/ día",              "pt": "/ dia"],
        "recurring.freq.s.weekly":["fr": "/ semaine",            "en": "/ week",              "es": "/ sem.",             "pt": "/ sem."],
        "recurring.freq.s.biweekly":["fr":"/ 2 sem.",            "en": "/ 2 wks",             "es": "/ 2 sem.",           "pt": "/ 2 sem."],
        "recurring.freq.s.monthly":["fr":"/ mois",               "en": "/ month",             "es": "/ mes",              "pt": "/ mês"],
        "recurring.freq.s.quarterly":["fr":"/ trim.",            "en": "/ qtr",               "es": "/ trim.",            "pt": "/ trim."],
        "recurring.freq.s.yearly":["fr": "/ an",                 "en": "/ year",              "es": "/ año",              "pt": "/ ano"],

        // MARK: - Loans
        "loan.title":           ["fr": "Prêts",                  "en": "Loans",               "es": "Préstamos",          "pt": "Empréstimos"],
        "loan.create":          ["fr": "Nouveau prêt",           "en": "New Loan",            "es": "Nuevo préstamo",     "pt": "Novo empréstimo"],
        "loan.edit":            ["fr": "Modifier le prêt",       "en": "Edit Loan",           "es": "Editar préstamo",    "pt": "Editar empréstimo"],
        "loan.totalDebt":       ["fr": "Dette totale",           "en": "Total Debt",          "es": "Deuda total",        "pt": "Dívida total"],
        "loan.identify":        ["fr": "Identification",         "en": "Identification",      "es": "Identificación",     "pt": "Identificação"],
        "loan.labelPlaceholder":["fr": "ex. Hypothèque principale","en": "e.g. Main Mortgage","es": "ej. Hipoteca principal","pt": "ex. Hipoteca principal"],
        "loan.lenderPlaceholder":["fr":"ex. Banque Nationale",   "en": "e.g. National Bank",  "es": "ej. Banco Nacional", "pt": "ex. Banco Nacional"],
        "loan.amountRate":      ["fr": "Montant et taux",        "en": "Amount & Rate",       "es": "Monto y tasa",       "pt": "Valor e taxa"],
        "loan.principal":       ["fr": "Montant emprunté",       "en": "Principal Amount",    "es": "Monto prestado",     "pt": "Valor emprestado"],
        "loan.annualRate":      ["fr": "Taux d'intérêt annuel",  "en": "Annual Interest Rate","es": "Tasa de interés anual","pt": "Taxa de juros anual"],
        "loan.annualRate.sub":  ["fr": "Taux nominal tel qu'inscrit au contrat","en": "Nominal rate as stated in your contract","es": "Tasa nominal según tu contrato","pt": "Taxa nominal conforme seu contrato"],
        "loan.duration":        ["fr": "Durée et versements",    "en": "Term & Payments",     "es": "Plazo y pagos",      "pt": "Prazo e pagamentos"],
        "loan.term":            ["fr": "Durée",                  "en": "Term",                "es": "Plazo",              "pt": "Prazo"],
        "loan.paymentFreq":     ["fr": "Fréquence des versements","en": "Payment Frequency",  "es": "Frecuencia de pago", "pt": "Frequência de pagamento"],
        "loan.firstPayment":    ["fr": "Premier versement",      "en": "First Payment",       "es": "Primer pago",        "pt": "Primeiro pagamento"],
        "loan.debitAccount":    ["fr": "Compte débité",          "en": "Debited Account",     "es": "Cuenta debitada",    "pt": "Conta debitada"],
        "loan.noAccount":       ["fr": "Aucun (suivi seulement)","en": "None (tracking only)","es": "Ninguna (solo seguimiento)","pt": "Nenhuma (somente rastreamento)"],
        "loan.summary":         ["fr": "Résumé calculé",         "en": "Calculated Summary",  "es": "Resumen calculado",  "pt": "Resumo calculado"],
        "loan.summary.footer":  ["fr": "Calcul basé sur les informations saisies. Vérifiez votre contrat de prêt pour les conditions exactes.", "en": "Calculation based on entered data. Check your loan contract for exact terms.", "es": "Cálculo basado en los datos ingresados. Verifica tu contrato para términos exactos.", "pt": "Cálculo baseado nos dados inseridos. Verifique seu contrato para termos exatos."],
        "loan.createRecurring": ["fr": "Créer un versement récurrent","en": "Create Recurring Payment","es": "Crear pago recurrente","pt": "Criar pagamento recorrente"],
        "loan.createRecurring.sub":["fr":"Enregistre automatiquement chaque paiement dans vos transactions","en": "Automatically records each payment in your transactions","es": "Registra automáticamente cada pago en tus transacciones","pt": "Registra automaticamente cada pagamento nas transações"],
        "loan.delete":          ["fr": "Supprimer ce prêt",      "en": "Delete This Loan",    "es": "Eliminar este préstamo","pt": "Excluir este empréstimo"],
        "loan.delete.footer":   ["fr": "Supprime le prêt et son versement récurrent associé. Les transactions déjà enregistrées sont conservées.", "en": "Deletes the loan and its recurring payment. Already recorded transactions are kept.", "es": "Elimina el préstamo y su pago recurrente. Las transacciones ya registradas se conservan.", "pt": "Exclui o empréstimo e seu pagamento recorrente. As transações já registradas são mantidas."],
        "loan.situation":       ["fr": "Situation actuelle",     "en": "Current Status",      "es": "Situación actual",   "pt": "Situação atual"],
        "loan.originalPrincipal":["fr":"Capital initial",        "en": "Original Principal",  "es": "Capital inicial",    "pt": "Capital original"],
        "loan.principalPaid":   ["fr": "Capital remboursé",      "en": "Principal Paid",      "es": "Capital pagado",     "pt": "Capital pago"],
        "loan.interestPaid":    ["fr": "Intérêts payés à ce jour","en": "Interest Paid to Date","es": "Intereses pagados a la fecha","pt": "Juros pagos até hoje"],
        "loan.paymentsMade":    ["fr": "Versements effectués",   "en": "Payments Made",       "es": "Pagos realizados",   "pt": "Pagamentos realizados"],
        "loan.paymentsRemaining":["fr":"Versements restants",    "en": "Payments Remaining",  "es": "Pagos restantes",    "pt": "Pagamentos restantes"],
        "loan.nextPayment":     ["fr": "Prochain versement",     "en": "Next Payment",        "es": "Próximo pago",       "pt": "Próximo pagamento"],
        "loan.totalCost":       ["fr": "Coût total",             "en": "Total Cost",          "es": "Costo total",        "pt": "Custo total"],
        "loan.totalInterest":   ["fr": "Total des intérêts",     "en": "Total Interest",      "es": "Intereses totales",  "pt": "Total de juros"],
        "loan.totalPaid":       ["fr": "Coût total du prêt",     "en": "Total Loan Cost",     "es": "Costo total del préstamo","pt": "Custo total do empréstimo"],
        "loan.progressSplit":   ["fr": "Répartition capital / intérêts","en": "Principal / Interest Split","es": "Distribución capital / intereses","pt": "Distribuição capital / juros"],
        "loan.upcoming12":      ["fr": "Prochains versements (12 mois)","en": "Upcoming Payments (12 months)","es": "Próximos pagos (12 meses)","pt": "Próximos pagamentos (12 meses)"],
        "loan.fullSchedule":    ["fr": "Voir le tableau complet (%d versements)","en": "View Full Schedule (%d payments)","es": "Ver tabla completa (%d pagos)","pt": "Ver tabela completa (%d pagamentos)"],
        "loan.amortization":    ["fr": "Tableau d'amortissement","en": "Amortization Schedule","es": "Tabla de amortización","pt": "Tabela de amortização"],
        "loan.paymentNum":      ["fr": "Versement #%d",          "en": "Payment #%d",         "es": "Pago #%d",           "pt": "Pagamento #%d"],
        "loan.estimatedEnd":    ["fr": "Date de fin estimée",    "en": "Estimated End Date",  "es": "Fecha estimada de fin","pt": "Data estimada de fim"],
        "loan.savingsPayments": ["fr": "%d versements économisés","en": "%d payments saved",  "es": "%d pagos ahorrados", "pt": "%d pagamentos economizados"],
        "loan.paidOff":         ["fr": "Prêt entièrement remboursé.","en": "Loan fully paid off.","es": "Préstamo totalmente pagado.","pt": "Empréstimo totalmente pago."],
        "loan.type.mortgage":   ["fr": "Hypothèque",             "en": "Mortgage",            "es": "Hipoteca",           "pt": "Hipoteca"],
        "loan.type.auto":       ["fr": "Prêt automobile",        "en": "Auto Loan",           "es": "Préstamo de auto",   "pt": "Financiamento de veículo"],
        "loan.type.personal":   ["fr": "Prêt personnel",         "en": "Personal Loan",       "es": "Préstamo personal",  "pt": "Empréstimo pessoal"],
        "loan.type.student":    ["fr": "Prêt étudiant",          "en": "Student Loan",        "es": "Préstamo estudiantil","pt": "Empréstimo estudantil"],
        "loan.type.other":      ["fr": "Autre",                  "en": "Other",               "es": "Otro",               "pt": "Outro"],
        "loan.freq.monthly":    ["fr": "Mensuel",                "en": "Monthly",             "es": "Mensual",            "pt": "Mensal"],
        "loan.freq.biweeklyAcc":["fr": "Bihebdomadaire accéléré","en": "Biweekly Accelerated","es": "Quincenal acelerado", "pt": "Quinzenal acelerado"],
        "loan.freq.biweekly":   ["fr": "Bihebdomadaire",         "en": "Biweekly",            "es": "Quincenal",          "pt": "Quinzenal"],
        "loan.freq.weekly":     ["fr": "Hebdomadaire",           "en": "Weekly",              "es": "Semanal",            "pt": "Semanal"],
        "loan.compound.monthly":["fr": "Mensuelle",              "en": "Monthly",             "es": "Mensual",            "pt": "Mensal"],
        "loan.compound.semiAnnual":["fr":"Semestrielle (hypothèques CA)","en": "Semi-Annual (CA Mortgages)","es": "Semestral (hipotecas CA)","pt": "Semestral (hipotecas CA)"],
        "loan.compound.section":["fr": "Avancé",                 "en": "Advanced",            "es": "Avanzado",           "pt": "Avançado"],
        "loan.compound.footer": ["fr": "Les hypothèques canadiennes utilisent la capitalisation semestrielle (Loi sur les intérêts). Les prêts personnels et auto utilisent généralement la capitalisation mensuelle.", "en": "Canadian mortgages use semi-annual compounding (Interest Act). Personal and auto loans typically use monthly compounding.", "es": "Las hipotecas canadienses usan capitalización semestral. Los préstamos personales y de auto generalmente usan capitalización mensual.", "pt": "Hipotecas canadenses usam capitalização semestral. Empréstimos pessoais e de veículo geralmente usam capitalização mensal."],
        "loan.empty.title":     ["fr": "Aucun prêt enregistré",  "en": "No Loans Added",      "es": "Sin préstamos",      "pt": "Sem empréstimos"],
        "loan.empty.sub":       ["fr": "Ajoutez une hypothèque, un prêt auto ou personnel. FinTrack calculera automatiquement les mensualités et le tableau d'amortissement.", "en": "Add a mortgage, auto or personal loan. FinTrack will automatically calculate monthly payments and the amortization schedule.", "es": "Añade una hipoteca, préstamo de auto o personal. FinTrack calculará automáticamente las cuotas y el plan de amortización.", "pt": "Adicione uma hipoteca, financiamento de veículo ou empréstimo pessoal. O FinTrack calculará automaticamente as parcelas e a tabela de amortização."],
        "loan.add":             ["fr": "Ajouter un prêt",        "en": "Add a Loan",          "es": "Añadir un préstamo", "pt": "Adicionar um empréstimo"],

        // MARK: - Credit Lines
        "cl.title":            ["fr": "Marges de crédit",        "en": "Credit Lines",        "es": "Líneas de crédito",  "pt": "Linhas de crédito"],
        "cl.create":           ["fr": "Nouvelle marge de crédit","en": "New Credit Line",     "es": "Nueva línea de crédito","pt": "Nova linha de crédito"],
        "cl.edit":             ["fr": "Modifier la marge",       "en": "Edit Credit Line",    "es": "Editar línea",       "pt": "Editar linha"],
        "cl.namePlaceholder":  ["fr": "ex. Marge BNC, HELOC Desjardins","en": "e.g. HELOC, LOC BNC","es": "ej. Línea de crédito","pt": "ex. Linha de crédito"],
        "cl.limit":            ["fr": "Plafond autorisé",        "en": "Credit Limit",        "es": "Límite de crédito",  "pt": "Limite de crédito"],
        "cl.rate":             ["fr": "Taux d'intérêt annuel",   "en": "Annual Interest Rate","es": "Tasa de interés anual","pt": "Taxa de juros anual"],
        "cl.rate.sub":         ["fr": "Tel qu'indiqué dans votre contrat","en": "As stated in your contract","es": "Según tu contrato","pt": "Conforme seu contrato"],
        "cl.amountRate":       ["fr": "Montant et taux",         "en": "Amount & Rate",       "es": "Monto y tasa",       "pt": "Valor e taxa"],
        "cl.initialBalance":   ["fr": "Solde actuel utilisé",    "en": "Current Used Balance","es": "Saldo actual usado",  "pt": "Saldo atual utilizado"],
        "cl.initialBalance.section":["fr":"Solde initial",       "en": "Initial Balance",     "es": "Saldo inicial",      "pt": "Saldo inicial"],
        "cl.initialBalance.footer":["fr":"Entrez le montant actuellement utilisé sur cette marge. Vous pourrez ensuite ajouter des retraits et remboursements manuellement.", "en": "Enter the amount currently used on this line. You can then add draws and repayments manually.", "es": "Ingresa el monto actualmente usado en esta línea. Luego puedes añadir retiros y pagos manualmente.", "pt": "Insira o valor atualmente utilizado nesta linha. Você pode então adicionar saques e pagamentos manualmente."],
        "cl.monthlyInterest":  ["fr": "Intérêts mensuels estimés","en": "Estimated Monthly Interest","es": "Interés mensual estimado","pt": "Juros mensais estimados"],
        "cl.minPayment":       ["fr": "Paiement minimum",        "en": "Minimum Payment",     "es": "Pago mínimo",        "pt": "Pagamento mínimo"],
        "cl.minPayment.footer":["fr": "Utilisé pour estimer l'obligation mensuelle dans le flux de trésorerie.", "en": "Used to estimate the monthly obligation in cash flow.", "es": "Usado para estimar la obligación mensual en el flujo de caja.", "pt": "Usado para estimar a obrigação mensal no fluxo de caixa."],
        "cl.dailyRate":        ["fr": "Taux journalier",         "en": "Daily Rate",          "es": "Tasa diaria",        "pt": "Taxa diária"],
        "cl.entry.repayment":  ["fr": "Remboursement",           "en": "Repayment",           "es": "Pago",               "pt": "Pagamento"],
        "cl.entry.draw":       ["fr": "Retrait",                 "en": "Draw",                "es": "Retiro",             "pt": "Saque"],
        "cl.entry.interest":   ["fr": "Intérêts courus",         "en": "Accrued Interest",    "es": "Intereses acumulados","pt": "Juros acumulados"],
        "cl.addRepayment":     ["fr": "Enregistrer un remboursement","en": "Record Repayment", "es": "Registrar pago",     "pt": "Registrar pagamento"],
        "cl.addDraw":          ["fr": "Enregistrer un retrait",  "en": "Record Draw",         "es": "Registrar retiro",   "pt": "Registrar saque"],
        "cl.history":          ["fr": "Historique (%d)",         "en": "History (%d)",        "es": "Historial (%d)",     "pt": "Histórico (%d)"],
        "cl.noHistory":        ["fr": "Aucun mouvement pour l'instant.","en": "No movements yet.","es": "Sin movimientos aún.","pt": "Sem movimentos ainda."],
        "cl.balanceUsed":      ["fr": "Solde utilisé",           "en": "Used Balance",        "es": "Saldo usado",        "pt": "Saldo utilizado"],
        "cl.available":        ["fr": "Disponible",              "en": "Available",           "es": "Disponible",         "pt": "Disponível"],
        "cl.limit.short":      ["fr": "Plafond",                 "en": "Limit",               "es": "Límite",             "pt": "Limite"],
        "cl.used":             ["fr": "utilisé",                 "en": "used",                "es": "usado",              "pt": "utilizado"],
        "cl.evolution":        ["fr": "Évolution du solde",      "en": "Balance History",     "es": "Evolución del saldo","pt": "Evolução do saldo"],
        "cl.noMovements":      ["fr": "Aucun mouvement enregistré.","en": "No movements recorded.","es": "Sin movimientos registrados.","pt": "Sem movimentos registrados."],
        "cl.metrics":          ["fr": "Coût mensuel estimé",     "en": "Estimated Monthly Cost","es": "Costo mensual estimado","pt": "Custo mensal estimado"],
        "cl.recurringRepayment":["fr":"Remboursement récurrent", "en": "Recurring Repayment", "es": "Pago recurrente",    "pt": "Pagamento recorrente"],
        "cl.recurringRepayment.sub":["fr":"Enregistre automatiquement un paiement périodique","en":"Automatically records a periodic payment","es":"Registra automáticamente un pago periódico","pt":"Registra automaticamente um pagamento periódico"],
        "cl.delete":           ["fr": "Supprimer cette marge",   "en": "Delete This Credit Line","es": "Eliminar esta línea","pt": "Excluir esta linha"],
        "cl.delete.footer":    ["fr": "Supprime la marge et tout son historique de mouvements.", "en": "Deletes the credit line and all its movement history.", "es": "Elimina la línea de crédito y todo su historial.", "pt": "Exclui a linha de crédito e todo o seu histórico."],
        "cl.totalDebt":        ["fr": "Dette totale",            "en": "Total Debt",          "es": "Deuda total",        "pt": "Dívida total"],
        "cl.empty.title":      ["fr": "Aucune marge de crédit",  "en": "No Credit Lines",     "es": "Sin líneas de crédito","pt": "Sem linhas de crédito"],
        "cl.empty.sub":        ["fr": "Ajoutez vos marges de crédit pour suivre leur solde, les intérêts courus automatiquement et votre taux d'utilisation.", "en": "Add your credit lines to track their balance, automatically accrued interest, and utilization rate.", "es": "Añade tus líneas de crédito para seguir su saldo, intereses acumulados automáticamente y tasa de utilización.", "pt": "Adicione suas linhas de crédito para acompanhar o saldo, juros acumulados automaticamente e taxa de utilização."],
        "cl.add":              ["fr": "Ajouter une marge",       "en": "Add Credit Line",     "es": "Añadir línea",       "pt": "Adicionar linha"],
        "cl.associatedAccount":["fr": "Compte associé (optionnel)","en": "Associated Account (optional)","es": "Cuenta asociada (opcional)","pt": "Conta associada (opcional)"],
        "cl.preview":          ["fr": "Aperçu après opération",  "en": "Preview After Operation","es": "Vista previa",    "pt": "Prévia após operação"],
        "cl.newDraw":          ["fr": "Nouveau retrait",         "en": "New Draw",            "es": "Nuevo retiro",       "pt": "Novo saque"],
        "cl.newRepayment":     ["fr": "Remboursement",           "en": "Repayment",           "es": "Pago",               "pt": "Pagamento"],
        "cl.compound.daily":   ["fr": "Quotidienne (marges CA)", "en": "Daily (CA Lines)",    "es": "Diaria (líneas CA)", "pt": "Diária (linhas CA)"],
        "cl.compound.monthly": ["fr": "Mensuelle",               "en": "Monthly",             "es": "Mensual",            "pt": "Mensal"],
        "cl.minType.interestOnly":["fr":"Intérêts seulement",    "en": "Interest Only",       "es": "Solo intereses",     "pt": "Somente juros"],
        "cl.minType.percent":  ["fr": "% du solde",              "en": "% of Balance",        "es": "% del saldo",        "pt": "% do saldo"],
        "cl.minType.fixed":    ["fr": "Montant fixe",            "en": "Fixed Amount",        "es": "Monto fijo",         "pt": "Valor fixo"],

        // MARK: - Savings Projects
        "savings.title":        ["fr": "Projets d'épargne",       "en": "Savings Goals",       "es": "Metas de ahorro",    "pt": "Metas de poupança"],
        "savings.create":       ["fr": "Créer un projet",         "en": "Create Goal",         "es": "Crear meta",         "pt": "Criar meta"],
        "savings.createNew":    ["fr": "Nouveau projet",          "en": "New Goal",            "es": "Nueva meta",         "pt": "Nova meta"],
        "savings.edit":         ["fr": "Modifier le projet",      "en": "Edit Goal",           "es": "Editar meta",        "pt": "Editar meta"],
        "savings.totalSavings": ["fr": "Épargne totale (%@)",     "en": "Total Savings (%@)",  "es": "Ahorro total (%@)",  "pt": "Poupança total (%@)"],
        "savings.myProjects":   ["fr": "Mes projets (%d)",        "en": "My Goals (%d)",       "es": "Mis metas (%d)",     "pt": "Minhas metas (%d)"],
        "savings.archived":     ["fr": "Archivés (%d)",           "en": "Archived (%d)",       "es": "Archivados (%d)",    "pt": "Arquivados (%d)"],
        "savings.target":       ["fr": "Objectif",                "en": "Goal",                "es": "Meta",               "pt": "Meta"],
        "savings.targetAmount": ["fr": "Montant cible",           "en": "Target Amount",       "es": "Monto objetivo",     "pt": "Valor alvo"],
        "savings.currentAmount":["fr": "Montant actuel",          "en": "Current Amount",      "es": "Monto actual",       "pt": "Valor atual"],
        "savings.alreadySaved": ["fr": "Montant déjà épargné",    "en": "Amount Already Saved","es": "Monto ya ahorrado",  "pt": "Valor já poupado"],
        "savings.contribution": ["fr": "Contribution mensuelle",  "en": "Monthly Contribution","es": "Contribución mensual","pt": "Contribuição mensal"],
        "savings.contribution.section":["fr":"Versement mensuel depuis le surplus","en": "Monthly Payment from Surplus","es": "Pago mensual del superávit","pt": "Pagamento mensal do excedente"],
        "savings.contribution.footer":["fr":"Ce montant sera déduit du surplus mensuel affiché dans le flux de trésorerie.", "en": "This amount will be deducted from the monthly surplus shown in cash flow.", "es": "Este monto se deducirá del superávit mensual en el flujo de caja.", "pt": "Este valor será deduzido do excedente mensal no fluxo de caixa."],
        "savings.trackViaAccount":["fr":"Suivre via un compte",   "en": "Track via Account",   "es": "Seguir por cuenta",  "pt": "Acompanhar por conta"],
        "savings.trackViaAccount.sub":["fr":"Le montant épargné = solde du compte choisi","en": "Saved amount = chosen account balance","es": "Monto ahorrado = saldo de la cuenta","pt": "Valor poupado = saldo da conta"],
        "savings.defineTarget": ["fr": "Définir un montant cible","en": "Set a Target Amount", "es": "Definir monto objetivo","pt": "Definir valor alvo"],
        "savings.deadline":     ["fr": "Date limite",             "en": "Deadline",            "es": "Fecha límite",       "pt": "Data limite"],
        "savings.deadline.sub": ["fr": "L'app calculera la contribution requise","en": "The app will calculate the required contribution","es": "La app calculará la contribución requerida","pt": "O app calculará a contribuição necessária"],
        "savings.deadlinePicker":["fr":"Atteindre l'objectif avant le","en": "Reach goal by",  "es": "Alcanzar meta antes del","pt": "Atingir meta antes de"],
        "savings.projection":   ["fr": "Projection",              "en": "Projection",          "es": "Proyección",         "pt": "Projeção"],
        "savings.projectionEmpty":["fr":"Définissez une contribution mensuelle pour voir la projection.","en": "Set a monthly contribution to see the projection.","es": "Define una contribución mensual para ver la proyección.","pt": "Defina uma contribuição mensal para ver a projeção."],
        "savings.indicators":   ["fr": "Indicateurs",             "en": "Indicators",          "es": "Indicadores",        "pt": "Indicadores"],
        "savings.targetReach":  ["fr": "Date d'atteinte estimée", "en": "Estimated Reach Date","es": "Fecha estimada de alcance","pt": "Data estimada de alcance"],
        "savings.monthsLeft":   ["fr": "Mois restants",           "en": "Months Remaining",    "es": "Meses restantes",    "pt": "Meses restantes"],
        "savings.requiredContrib":["fr":"Contribution requise (échéance)","en": "Required Contribution (deadline)","es": "Contribución requerida (plazo)","pt": "Contribuição necessária (prazo)"],
        "savings.defineContrib":["fr": "Définissez une contribution mensuelle","en": "Set a monthly contribution","es": "Define una contribución mensual","pt": "Defina uma contribuição mensal"],
        "savings.requiredForDeadline":["fr":"Contribution requise pour l'échéance","en": "Required for deadline","es": "Requerida para el plazo","pt": "Necessária para o prazo"],
        "savings.goalReached":  ["fr": "Objectif atteint ! 🎉",   "en": "Goal Reached! 🎉",    "es": "¡Meta alcanzada! 🎉", "pt": "Meta atingida! 🎉"],
        "savings.freeAccumulation":["fr":"Accumulation libre",    "en": "Free Accumulation",   "es": "Acumulación libre",  "pt": "Acumulação livre"],
        "savings.delete":       ["fr": "Supprimer ce projet",     "en": "Delete This Goal",    "es": "Eliminar esta meta", "pt": "Excluir esta meta"],
        "savings.empty.title":  ["fr": "Aucun projet d'épargne",  "en": "No Savings Goals",    "es": "Sin metas de ahorro","pt": "Sem metas de poupança"],
        "savings.empty.sub":    ["fr": "Définissez un objectif — voyage, fonds d'urgence, achat — et FinTrack calculera quand vous l'atteindrez en fonction de votre surplus mensuel.", "en": "Set a goal — trip, emergency fund, purchase — and FinTrack will calculate when you'll reach it based on your monthly surplus.", "es": "Define una meta — viaje, fondo de emergencia, compra — y FinTrack calculará cuándo la alcanzarás según tu superávit mensual.", "pt": "Defina uma meta — viagem, fundo de emergência, compra — e o FinTrack calculará quando você a atingirá com base no seu excedente mensal."],
        "savings.goalReached.check":["fr":"Objectif atteint ✓",   "en": "Goal Reached ✓",      "es": "Meta alcanzada ✓",   "pt": "Meta atingida ✓"],
        "savings.scrubHint":    ["fr": "Glissez pour explorer la projection","en": "Slide to explore the projection","es": "Desliza para explorar la proyección","pt": "Deslize para explorar a projeção"],
        "savings.still":        ["fr": "Encore",                  "en": "Still",               "es": "Aún",                "pt": "Ainda"],
        "savings.currentAmount.section":["fr":"Montant actuel",   "en": "Current Amount",      "es": "Monto actual",       "pt": "Valor atual"],

        // MARK: - Cash Flow
        "cashflow.title":       ["fr": "Flux mensuel",            "en": "Monthly Cash Flow",   "es": "Flujo mensual",      "pt": "Fluxo mensal"],
        "cashflow.estimated":   ["fr": "Flux mensuel estimé",     "en": "Estimated Monthly Flow","es": "Flujo mensual estimado","pt": "Fluxo mensal estimado"],
        "cashflow.monthlyIncome":["fr":"Revenus mensuels estimés","en": "Estimated Monthly Income","es": "Ingresos mensuales estimados","pt": "Receita mensal estimada"],
        "cashflow.recurringExp":["fr": "Dépenses récurrentes",    "en": "Recurring Expenses",  "es": "Gastos recurrentes", "pt": "Despesas recorrentes"],
        "cashflow.loanPayments":["fr": "Remboursements de prêts", "en": "Loan Repayments",     "es": "Pagos de préstamos", "pt": "Pagamentos de empréstimos"],
        "cashflow.clPayments":  ["fr": "Marges de crédit (paiements minima)","en": "Credit Lines (minimum payments)","es": "Líneas de crédito (pagos mínimos)","pt": "Linhas de crédito (pagamentos mínimos)"],
        "cashflow.totalIncome": ["fr": "Total revenus",           "en": "Total Income",        "es": "Total ingresos",     "pt": "Total receitas"],
        "cashflow.totalExp":    ["fr": "Total dépenses",          "en": "Total Expenses",      "es": "Total gastos",       "pt": "Total despesas"],
        "cashflow.totalLoans":  ["fr": "Total remboursements",    "en": "Total Repayments",    "es": "Total pagos",        "pt": "Total pagamentos"],
        "cashflow.totalCL":     ["fr": "Total paiements minima",  "en": "Total Min. Payments", "es": "Total pagos mínimos","pt": "Total pagamentos mínimos"],
        "cashflow.netResult":   ["fr": "Résultat net",            "en": "Net Result",          "es": "Resultado neto",     "pt": "Resultado líquido"],
        "cashflow.surplus":     ["fr": "≈ Surplus mensuel",       "en": "≈ Monthly Surplus",   "es": "≈ Superávit mensual","pt": "≈ Excedente mensal"],
        "cashflow.surplus.before":["fr":"Avant allocation aux projets","en": "Before project allocations","es": "Antes de asignaciones","pt": "Antes das alocações"],
        "cashflow.allocation":  ["fr": "Allocation aux projets d'épargne","en": "Savings Goal Allocations","es": "Asignaciones a metas","pt": "Alocações para metas"],
        "cashflow.free":        ["fr": "Libre (non alloué)",      "en": "Free (Unallocated)",  "es": "Libre (no asignado)","pt": "Livre (não alocado)"],
        "cashflow.warning.deficit":["fr":"Attention : les sorties dépassent les entrées ce mois-ci.","en": "Warning: outflows exceed inflows this month.","es": "Atención: las salidas superan las entradas este mes.","pt": "Atenção: saídas superam entradas este mês."],
        "cashflow.warning.overAllocated":["fr":"Les allocations dépassent le surplus. Réduisez certaines contributions.","en": "Allocations exceed the surplus. Reduce some contributions.","es": "Las asignaciones superan el superávit. Reduce algunas contribuciones.","pt": "Alocações superam o excedente. Reduza algumas contribuições."],
        "cashflow.note":        ["fr": "Basé uniquement sur vos transactions et prêts récurrents. Les dépenses non planifiées ne sont pas incluses.", "en": "Based only on your recurring transactions and loans. Unplanned expenses are not included.", "es": "Basado solo en tus transacciones y préstamos recurrentes. Los gastos no planificados no están incluidos.", "pt": "Baseado apenas em suas transações e empréstimos recorrentes. Despesas não planejadas não estão incluídas."],

        // MARK: - Analytics
        "analytics.title":       ["fr": "Analyse & Projection",   "en": "Analytics & Projection","es": "Análisis y Proyección","pt": "Análise e Projeção"],
        "analytics.balanceProjection":["fr":"Projection de solde","en": "Balance Projection",  "es": "Proyección de saldo","pt": "Projeção de saldo"],
        "analytics.incomeExpense":["fr":"Revenus vs Dépenses",    "en": "Income vs Expenses",  "es": "Ingresos vs Gastos", "pt": "Receitas vs Despesas"],
        "analytics.categoryBreakdown":["fr":"Répartition des dépenses","en": "Expense Breakdown","es": "Desglose de gastos","pt": "Detalhamento de despesas"],
        "analytics.real":        ["fr": "Réel",                   "en": "Actual",              "es": "Real",               "pt": "Real"],
        "analytics.projection":  ["fr": "Projection",             "en": "Projection",          "es": "Proyección",         "pt": "Projeção"],
        "analytics.todayShort":  ["fr": "Auj.",                   "en": "Today",               "es": "Hoy",                "pt": "Hoje"],
        "analytics.thisMonth":   ["fr": "Ce mois",                "en": "This Month",          "es": "Este mes",           "pt": "Este mês"],
        "analytics.scrubHint":   ["fr": "Appuyez et glissez pour explorer","en": "Tap and drag to explore","es": "Toca y desliza para explorar","pt": "Toque e arraste para explorar"],
        "analytics.tapBar":      ["fr": "Touchez une barre",      "en": "Tap a bar",           "es": "Toca una barra",     "pt": "Toque em uma barra"],
        "analytics.inPeriod":    ["fr": "dans %@",                "en": "in %@",               "es": "en %@",              "pt": "em %@"],
        "analytics.zero":        ["fr": "Zéro",                   "en": "Zero",                "es": "Cero",               "pt": "Zero"],
        "analytics.negativeAlert":["fr":"Solde projeté négatif sur la période","en": "Projected balance goes negative in this period","es": "El saldo proyectado se vuelve negativo","pt": "O saldo projetado fica negativo neste período"],
        "analytics.budget":      ["fr": "Budget & Épargne",       "en": "Budget & Savings",    "es": "Presupuesto y Ahorro","pt": "Orçamento e Poupança"],

        // MARK: - Settings
        "settings.title":        ["fr": "Réglages",               "en": "Settings",            "es": "Ajustes",            "pt": "Configurações"],
        "settings.data":         ["fr": "Données",                "en": "Data",                "es": "Datos",              "pt": "Dados"],
        "settings.stats":        ["fr": "Statistiques",           "en": "Statistics",          "es": "Estadísticas",       "pt": "Estatísticas"],
        "settings.accountCount": ["fr": "Nombre de comptes",      "en": "Number of Accounts",  "es": "Número de cuentas",  "pt": "Número de contas"],
        "settings.txCount":      ["fr": "Nombre de transactions", "en": "Number of Transactions","es": "Número de transacciones","pt": "Número de transações"],
        "settings.dangerZone":   ["fr": "Zone dangereuse",        "en": "Danger Zone",         "es": "Zona de peligro",    "pt": "Zona de perigo"],
        "settings.resetAll":     ["fr": "Réinitialiser toutes les données","en": "Reset All Data","es": "Restablecer todos los datos","pt": "Redefinir todos os dados"],
        "settings.resetAll.footer":["fr":"Supprime tous les comptes, transactions et catégories personnalisées. Les catégories par défaut seront recréées. Cette action est irréversible.", "en": "Deletes all accounts, transactions, and custom categories. Default categories will be recreated. This action is irreversible.", "es": "Elimina todas las cuentas, transacciones y categorías personalizadas. Las categorías predeterminadas se recrearán. Esta acción es irreversible.", "pt": "Exclui todas as contas, transações e categorias personalizadas. As categorias padrão serão recriadas. Esta ação é irreversível."],
        "settings.about":        ["fr": "À propos",               "en": "About",               "es": "Acerca de",          "pt": "Sobre"],
        "settings.version":      ["fr": "Version",                "en": "Version",             "es": "Versión",            "pt": "Versão"],
        "settings.storage":      ["fr": "Stockage",               "en": "Storage",             "es": "Almacenamiento",     "pt": "Armazenamento"],
        "settings.storage.local":["fr": "Local (sur cet appareil)","en": "Local (on this device)","es": "Local (en este dispositivo)","pt": "Local (neste dispositivo)"],
        "settings.exportCSV":    ["fr": "Exporter les transactions (CSV)","en": "Export Transactions (CSV)","es": "Exportar transacciones (CSV)","pt": "Exportar transações (CSV)"],
        "settings.resetPrompt":  ["fr": "Tout réinitialiser ?",   "en": "Reset Everything?",   "es": "¿Restablecer todo?", "pt": "Redefinir tudo?"],
        "settings.resetMessage": ["fr": "Toutes vos données seront supprimées. Cette action est irréversible.", "en": "All your data will be deleted. This action is irreversible.", "es": "Todos tus datos serán eliminados. Esta acción es irreversible.", "pt": "Todos os seus dados serão excluídos. Esta ação é irreversível."],
        "settings.language":     ["fr": "Langue",                 "en": "Language",            "es": "Idioma",             "pt": "Idioma"],
        "settings.language.section":["fr":"Langue de l'application","en": "App Language",      "es": "Idioma de la app",   "pt": "Idioma do app"],





        // MARK: - iCloud / CloudKit
        "icloud.section":      ["fr": "iCloud",                                    "en": "iCloud",                                  "es": "iCloud",                                  "pt": "iCloud"],
        "icloud.manage":       ["fr": "Synchronisation iCloud",                    "en": "iCloud Sync",                             "es": "Sincronización iCloud",                   "pt": "Sincronização iCloud"],
        "icloud.status":       ["fr": "Statut",                                    "en": "Status",                                  "es": "Estado",                                  "pt": "Status"],
        "icloud.available":    ["fr": "iCloud disponible ✓",                       "en": "iCloud Available ✓",                      "es": "iCloud disponible ✓",                     "pt": "iCloud disponível ✓"],
        "icloud.unavailable":  ["fr": "iCloud non disponible",                     "en": "iCloud Not Available",                    "es": "iCloud no disponible",                    "pt": "iCloud não disponível"],
        "icloud.restricted":   ["fr": "iCloud restreint (contrôle parental)",      "en": "iCloud Restricted (Parental Controls)",   "es": "iCloud restringido (control parental)",   "pt": "iCloud restrito (controle parental)"],
        "icloud.noAccount":    ["fr": "Aucun compte iCloud — connectez-vous dans Réglages iOS", "en": "No iCloud Account — sign in via iOS Settings", "es": "Sin cuenta iCloud — inicia sesión en Ajustes", "pt": "Sem conta iCloud — entre nas Configurações iOS"],
        "icloud.sync.info":    ["fr": "Vos données sont synchronisées automatiquement entre tous vos appareils Apple connectés au même compte iCloud.", "en": "Your data is automatically synced across all your Apple devices signed in to the same iCloud account.", "es": "Tus datos se sincronizan automáticamente en todos tus dispositivos Apple con la misma cuenta iCloud.", "pt": "Seus dados são sincronizados automaticamente em todos os seus dispositivos Apple com a mesma conta iCloud."],
        "icloud.openSettings": ["fr": "Ouvrir Réglages iOS",                       "en": "Open iOS Settings",                       "es": "Abrir Ajustes de iOS",                    "pt": "Abrir Configurações do iOS"],
        "icloud.container":    ["fr": "Conteneur CloudKit",                        "en": "CloudKit Container",                      "es": "Contenedor CloudKit",                     "pt": "Container CloudKit"],

        // MARK: - Notifications
        "notification.section":      ["fr": "Rappel",                              "en": "Reminder",                       "es": "Recordatorio",                  "pt": "Lembrete"],
        "notification.enable":       ["fr": "Activer le rappel",                   "en": "Enable Reminder",                "es": "Activar recordatorio",          "pt": "Ativar lembrete"],
        "notification.daysBefore":   ["fr": "Rappel",                              "en": "Remind me",                      "es": "Recordarme",                    "pt": "Me lembrar"],
        "notification.dayBefore.1":  ["fr": "La veille",                           "en": "The day before",                 "es": "El día anterior",               "pt": "No dia anterior"],
        "notification.dayBefore.n":  ["fr": "%d jours avant",                      "en": "%d days before",                 "es": "%d días antes",                 "pt": "%d dias antes"],
        "notification.tomorrow":     ["fr": "demain",                              "en": "tomorrow",                       "es": "mañana",                        "pt": "amanhã"],
        "notification.inDays":       ["fr": "dans %d jours",                       "en": "in %d days",                     "es": "en %d días",                    "pt": "em %d dias"],
        "notification.settings":     ["fr": "Notifications",                       "en": "Notifications",                  "es": "Notificaciones",                "pt": "Notificações"],
        "notification.manage":       ["fr": "Gérer les rappels",                   "en": "Manage Reminders",               "es": "Gestionar recordatorios",       "pt": "Gerenciar lembretes"],
        "notification.status":       ["fr": "Statut",                              "en": "Status",                         "es": "Estado",                        "pt": "Status"],
        "notification.authorized":   ["fr": "Autorisées ✓",                        "en": "Authorized ✓",                   "es": "Autorizadas ✓",                 "pt": "Autorizadas ✓"],
        "notification.denied":       ["fr": "Refusées — modifier dans Réglages iOS","en": "Denied — change in iOS Settings","es": "Denegadas — cambiar en Ajustes","pt": "Negadas — alterar nas Configurações"],
        "notification.pending":      ["fr": "Rappels programmés",                  "en": "Scheduled Reminders",            "es": "Recordatorios programados",     "pt": "Lembretes programados"],
        "notification.reschedule":   ["fr": "Reprogrammer tous les rappels",       "en": "Reschedule All Reminders",       "es": "Reprogramar recordatorios",     "pt": "Reprogramar lembretes"],
        "notification.openSettings": ["fr": "Ouvrir les réglages iOS",             "en": "Open iOS Settings",              "es": "Abrir Ajustes de iOS",          "pt": "Abrir Configurações do iOS"],
        "notification.cancelAll":    ["fr": "Annuler tous les rappels",            "en": "Cancel All Reminders",           "es": "Cancelar todos los recordatorios","pt": "Cancelar todos os lembretes"],

        // MARK: - Bank picker
        "bank.useCustom": ["fr": "Utiliser ce nom personnalisé", "en": "Use this custom name", "es": "Usar este nombre personalizado", "pt": "Usar este nome personalizado"],

        // MARK: - Prepayments
        "prepayment.title":          ["fr": "Versements anticipés",            "en": "Prepayments",                "es": "Pagos anticipados",             "pt": "Pagamentos antecipados"],
        "prepayment.oneTime":        ["fr": "Ponctuel",                         "en": "One-Time",                   "es": "Puntual",                       "pt": "Pontual"],
        "prepayment.recurring":      ["fr": "Récurrent",                        "en": "Recurring",                  "es": "Recurrente",                    "pt": "Recorrente"],
        "prepayment.add":            ["fr": "Ajouter un versement anticipé",    "en": "Add Prepayment",             "es": "Añadir pago anticipado",        "pt": "Adicionar pagamento antecipado"],
        "prepayment.create":         ["fr": "Nouveau versement anticipé",       "en": "New Prepayment",             "es": "Nuevo pago anticipado",         "pt": "Novo pagamento antecipado"],
        "prepayment.edit":           ["fr": "Modifier le versement anticipé",   "en": "Edit Prepayment",            "es": "Editar pago anticipado",        "pt": "Editar pagamento antecipado"],
        "prepayment.startDate.oneTime":["fr":"Date du versement",               "en": "Payment Date",               "es": "Fecha del pago",                "pt": "Data do pagamento"],
        "prepayment.startDate.recurring":["fr":"Date de début",                 "en": "Start Date",                 "es": "Fecha de inicio",               "pt": "Data de início"],
        "prepayment.impact":         ["fr": "Impact des versements anticipés",  "en": "Prepayment Impact",          "es": "Impacto de pagos anticipados",  "pt": "Impacto dos pagamentos antecipados"],
        "prepayment.savings.payments":["fr": "%d versements économisés",        "en": "%d payments saved",          "es": "%d pagos ahorrados",            "pt": "%d pagamentos economizados"],
        "prepayment.savings.interest":["fr": "Intérêts économisés",             "en": "Interest Saved",             "es": "Intereses ahorrados",           "pt": "Juros economizados"],
        "prepayment.newPayoffDate":  ["fr": "Nouvelle date de fin",             "en": "New Payoff Date",            "es": "Nueva fecha de fin",            "pt": "Nova data de quitação"],
        "prepayment.original":       ["fr": "Sans versements anticipés",        "en": "Without Prepayments",        "es": "Sin pagos anticipados",         "pt": "Sem pagamentos antecipados"],
        "prepayment.deletePrompt":   ["fr": "Supprimer ce versement anticipé ?","en": "Delete this prepayment?",    "es": "¿Eliminar este pago anticipado?","pt": "Excluir este pagamento antecipado?"],
        "prepayment.empty.title":    ["fr": "Aucun versement anticipé",         "en": "No Prepayments",             "es": "Sin pagos anticipados",         "pt": "Sem pagamentos antecipados"],
        "prepayment.empty.sub":      ["fr": "Réduisez vos intérêts en ajoutant un versement ponctuel ou récurrent sur le capital.", "en": "Reduce your interest by adding a one-time or recurring payment toward the principal.", "es": "Reduce tus intereses añadiendo un pago puntual o recurrente al capital.", "pt": "Reduza seus juros adicionando um pagamento pontual ou recorrente ao principal."],

        // MARK: - Categories
        "category.title":       ["fr": "Catégories",              "en": "Categories",          "es": "Categorías",         "pt": "Categorias"],
        "category.manage":      ["fr": "Gérer les catégories",    "en": "Manage Categories",   "es": "Gestionar categorías","pt": "Gerenciar categorias"],
        "category.expenses":    ["fr": "Dépenses (%d)",           "en": "Expenses (%d)",       "es": "Gastos (%d)",        "pt": "Despesas (%d)"],
        "category.incomes":     ["fr": "Revenus (%d)",            "en": "Income (%d)",         "es": "Ingresos (%d)",      "pt": "Receitas (%d)"],
        "category.default":     ["fr": "Par défaut",              "en": "Default",             "es": "Predeterminada",     "pt": "Padrão"],
        "category.create":      ["fr": "Nouvelle catégorie",      "en": "New Category",        "es": "Nueva categoría",    "pt": "Nova categoria"],
        "category.namePlaceholder":["fr":"Ex. Abonnements",       "en": "e.g. Subscriptions",  "es": "ej. Suscripciones",  "pt": "ex. Assinaturas"],
        "category.applicability":["fr":"Applicable à",            "en": "Applies To",          "es": "Aplicable a",        "pt": "Aplicável a"],
        "category.expense":     ["fr": "Dépenses",                "en": "Expenses",            "es": "Gastos",             "pt": "Despesas"],
        "category.income":      ["fr": "Revenus",                 "en": "Income",              "es": "Ingresos",           "pt": "Receitas"],
        "category.both":        ["fr": "Les deux",                "en": "Both",                "es": "Ambos",              "pt": "Ambos"],
        "category.type":        ["fr": "Type",                    "en": "Type",                "es": "Tipo",               "pt": "Tipo"],
    ]
    // swiftlint:enable line_length
}
